name: classroom-digital-twin
channels:
  - conda-forge
dependencies:
  - opencv=4.11.0
  - python=3.9.22
  - pip
  - pip:
      - pyside6==6.9.0
      - pyvista==0.45.2
      - pyvistaqt==0.11.2
      - qt-material==2.17